Fix: Add postinstall script to rebuild native modules for Linux
lightningcss and rollup have native bindings that need to be rebuilt
for Linux deployment on Render. This fixes the build error:
'Cannot find module ../lightningcss.linux-x64-gnu.node'